on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x.x
      - name: Lint Deno Module
        run: deno fmt --check
      - name: Build Deno Module
        run: deno run mod.ts
      - name: Test Deno Module
        run: deno test --allow-none
